name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xayn_design:
    path: ../../xayn_design

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: packages/xayn_design/assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: packages/xayn_design/assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: packages/xayn_design/assets/fonts/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
          weight: 400

  uses-material-design: true

  assets:
    # Including all the files in a directory is not supported for external packages
    # The following could be refactored when this issue is resolved
    # https://github.com/flutter/flutter/issues/27802

    # graphics
    - packages/xayn_design/assets/graphics/graphic_grid_view.svg
    - packages/xayn_design/assets/graphics/graphic_list_view.svg
    - packages/xayn_design/assets/graphics/graphic_news_only.svg
    - packages/xayn_design/assets/graphics/graphic_search_news.svg
    - packages/xayn_design/assets/graphics/graphic_search_only.svg

    # illustrations
    - packages/xayn_design/assets/illustrations/illustration_enable_camera.svg

    # logo
    - packages/xayn_design/assets/logo/icon_logo.svg
    - packages/xayn_design/assets/logo/xayn_logo.svg

    # icons
    - packages/xayn_design/assets/icons/brainy_disabled.svg
    - packages/xayn_design/assets/icons/brainy_disabled_dark.svg
    - packages/xayn_design/assets/icons/brainy_enabled.svg
    - packages/xayn_design/assets/icons/brainy_enabled_dark.svg
    - packages/xayn_design/assets/icons/icon_alert.svg
    - packages/xayn_design/assets/icons/icon_back.svg
    - packages/xayn_design/assets/icons/icon_binoculars.svg
    - packages/xayn_design/assets/icons/icon_book.svg
    - packages/xayn_design/assets/icons/icon_bookmark.svg
    - packages/xayn_design/assets/icons/icon_bookmark_active.svg
    - packages/xayn_design/assets/icons/icon_bug.svg
    - packages/xayn_design/assets/icons/icon_cancel.svg
    - packages/xayn_design/assets/icons/icon_check.svg
    - packages/xayn_design/assets/icons/icon_clock.svg
    - packages/xayn_design/assets/icons/icon_confetti.svg
    - packages/xayn_design/assets/icons/icon_cross.svg
    - packages/xayn_design/assets/icons/icon_devices.svg
    - packages/xayn_design/assets/icons/icon_down.svg
    - packages/xayn_design/assets/icons/icon_download.svg
    - packages/xayn_design/assets/icons/icon_edit.svg
    - packages/xayn_design/assets/icons/icon_filters.svg
    - packages/xayn_design/assets/icons/icon_filters_round.svg
    - packages/xayn_design/assets/icons/icon_forward.svg
    - packages/xayn_design/assets/icons/icon_gear.svg
    - packages/xayn_design/assets/icons/icon_globe.svg
    - packages/xayn_design/assets/icons/icon_heart.svg
    - packages/xayn_design/assets/icons/icon_home.svg
    - packages/xayn_design/assets/icons/icon_image.svg
    - packages/xayn_design/assets/icons/icon_info.svg
    - packages/xayn_design/assets/icons/icon_legal.svg
    - packages/xayn_design/assets/icons/icon_lightening.svg
    - packages/xayn_design/assets/icons/icon_menu.svg
    - packages/xayn_design/assets/icons/icon_minus.svg
    - packages/xayn_design/assets/icons/icon_moon.svg
    - packages/xayn_design/assets/icons/icon_moon_and_sun.svg
    - packages/xayn_design/assets/icons/icon_neutral.svg
    - packages/xayn_design/assets/icons/icon_new_tab.svg
    - packages/xayn_design/assets/icons/icon_news.svg
    - packages/xayn_design/assets/icons/icon_person.svg
    - packages/xayn_design/assets/icons/icon_play.svg
    - packages/xayn_design/assets/icons/icon_plus.svg
    - packages/xayn_design/assets/icons/icon_qr_code.svg
    - packages/xayn_design/assets/icons/icon_qr_scanner.svg
    - packages/xayn_design/assets/icons/icon_reader_mode.svg
    - packages/xayn_design/assets/icons/icon_reload.svg
    - packages/xayn_design/assets/icons/icon_rocket.svg
    - packages/xayn_design/assets/icons/icon_search.svg
    - packages/xayn_design/assets/icons/icon_share_android.svg
    - packages/xayn_design/assets/icons/icon_share_ios.svg
    - packages/xayn_design/assets/icons/icon_shield.svg
    - packages/xayn_design/assets/icons/icon_speech_bubbles.svg
    - packages/xayn_design/assets/icons/icon_sun.svg
    - packages/xayn_design/assets/icons/icon_tabs.svg
    - packages/xayn_design/assets/icons/icon_thumbs_down.svg
    - packages/xayn_design/assets/icons/icon_thumbs_up.svg
    - packages/xayn_design/assets/icons/icon_trash.svg
    - packages/xayn_design/assets/icons/icon_undo.svg
    - packages/xayn_design/assets/icons/icon_up.svg
    - packages/xayn_design/assets/icons/icon_video.svg
