name: xayn_design
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/xaynetwork/xayn_design

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: 2.0.3
  flutter_svg: 1.0.2
  flutter_switch: 0.3.2
  provider: 6.0.1
  rxdart: 0.27.3
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.17.0

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: packages/xayn_design/assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: packages/xayn_design/assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: NotoSerif
      fonts:
        - asset: packages/xayn_design/assets/fonts/NotoSerif-Regular.ttf
          weight: 400
        - asset: packages/xayn_design/assets/fonts/NotoSerif-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: packages/xayn_design/assets/fonts/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
          weight: 400

  uses-material-design: true
