name: xayn_design
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/xaynetwork/xayn_design

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: 2.0.3
  flutter_svg: 1.0.2
  flutter_switch: 0.3.2
  provider: 6.0.2
  rxdart: 0.27.3
  modal_bottom_sheet: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.17.0

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: packages/xayn_design/assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: packages/xayn_design/assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: NotoSerif
      fonts:
        - asset: packages/xayn_design/assets/fonts/NotoSerif-Regular.ttf
          weight: 400
        - asset: packages/xayn_design/assets/fonts/NotoSerif-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: packages/xayn_design/assets/fonts/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
          weight: 400

  uses-material-design: true

  assets:
    # Including all the files in a directory is not supported for external packages
    # The following could be refactored when this issue is resolved
    # https://github.com/flutter/flutter/issues/27802

    # graphics
    - packages/xayn_design/assets/graphics/forms_green.svg
    - packages/xayn_design/assets/graphics/forms_orange.svg
    - packages/xayn_design/assets/graphics/forms_purple.svg
    - packages/xayn_design/assets/graphics/grid_view.svg
    - packages/xayn_design/assets/graphics/list_view.svg
    - packages/xayn_design/assets/graphics/news_only.svg
    - packages/xayn_design/assets/graphics/search_news.svg
    - packages/xayn_design/assets/graphics/search_only.svg

    # illustrations
    - packages/xayn_design/assets/illustrations/enable_camera.svg
    - packages/xayn_design/assets/illustrations/brainy_disabled.svg
    - packages/xayn_design/assets/illustrations/brainy_disabled_dark.svg
    - packages/xayn_design/assets/illustrations/brainy_enabled.svg
    - packages/xayn_design/assets/illustrations/brainy_enabled_dark.svg
    - packages/xayn_design/assets/illustrations/flag_argentina.svg
    - packages/xayn_design/assets/illustrations/flag_australia.svg
    - packages/xayn_design/assets/illustrations/flag_austria.svg
    - packages/xayn_design/assets/illustrations/flag_belgium.svg
    - packages/xayn_design/assets/illustrations/flag_brazil.svg
    - packages/xayn_design/assets/illustrations/flag_canada.svg
    - packages/xayn_design/assets/illustrations/flag_chile.svg
    - packages/xayn_design/assets/illustrations/flag_china.svg
    - packages/xayn_design/assets/illustrations/flag_denmark.svg
    - packages/xayn_design/assets/illustrations/flag_finland.svg
    - packages/xayn_design/assets/illustrations/flag_france.svg
    - packages/xayn_design/assets/illustrations/flag_germany.svg
    - packages/xayn_design/assets/illustrations/flag_hong_kong.svg
    - packages/xayn_design/assets/illustrations/flag_india.svg
    - packages/xayn_design/assets/illustrations/flag_indonesia.svg
    - packages/xayn_design/assets/illustrations/flag_ireland.svg
    - packages/xayn_design/assets/illustrations/flag_italy.svg
    - packages/xayn_design/assets/illustrations/flag_japan.svg
    - packages/xayn_design/assets/illustrations/flag_malaysia.svg
    - packages/xayn_design/assets/illustrations/flag_mexico.svg
    - packages/xayn_design/assets/illustrations/flag_netherlands.svg
    - packages/xayn_design/assets/illustrations/flag_new_zealand.svg
    - packages/xayn_design/assets/illustrations/flag_norway.svg
    - packages/xayn_design/assets/illustrations/flag_philippines.svg
    - packages/xayn_design/assets/illustrations/flag_poland.svg
    - packages/xayn_design/assets/illustrations/flag_russia.svg
    - packages/xayn_design/assets/illustrations/flag_south_africa.svg
    - packages/xayn_design/assets/illustrations/flag_south_korea.svg
    - packages/xayn_design/assets/illustrations/flag_spain.svg
    - packages/xayn_design/assets/illustrations/flag_sweden.svg
    - packages/xayn_design/assets/illustrations/flag_switzerland.svg
    - packages/xayn_design/assets/illustrations/flag_taiwan.svg
    - packages/xayn_design/assets/illustrations/flag_turkey.svg
    - packages/xayn_design/assets/illustrations/flag_uk.svg
    - packages/xayn_design/assets/illustrations/flag_usa.svg
    # logo
    - packages/xayn_design/assets/logo/icon_logo.svg
    - packages/xayn_design/assets/logo/xayn_logo.svg

    # icons
    - packages/xayn_design/assets/icons/alert.svg
    - packages/xayn_design/assets/icons/arrow_down.svg
    - packages/xayn_design/assets/icons/arrow_left.svg
    - packages/xayn_design/assets/icons/arrow_right.svg
    - packages/xayn_design/assets/icons/arrow_up.svg
    - packages/xayn_design/assets/icons/binoculars.svg
    - packages/xayn_design/assets/icons/book.svg
    - packages/xayn_design/assets/icons/bookmark.svg
    - packages/xayn_design/assets/icons/bookmark_active.svg
    - packages/xayn_design/assets/icons/bug.svg
    - packages/xayn_design/assets/icons/carousel.svg
    - packages/xayn_design/assets/icons/check.svg
    - packages/xayn_design/assets/icons/clock.svg
    - packages/xayn_design/assets/icons/confetti.svg
    - packages/xayn_design/assets/icons/cross.svg
    - packages/xayn_design/assets/icons/devices.svg
    - packages/xayn_design/assets/icons/download.svg
    - packages/xayn_design/assets/icons/edit.svg
    - packages/xayn_design/assets/icons/filters.svg
    - packages/xayn_design/assets/icons/filters_round.svg
    - packages/xayn_design/assets/icons/font_size.svg
    - packages/xayn_design/assets/icons/gear.svg
    - packages/xayn_design/assets/icons/globe.svg
    - packages/xayn_design/assets/icons/heart.svg
    - packages/xayn_design/assets/icons/home.svg
    - packages/xayn_design/assets/icons/home_active.svg
    - packages/xayn_design/assets/icons/image.svg
    - packages/xayn_design/assets/icons/no_image.svg
    - packages/xayn_design/assets/icons/info.svg
    - packages/xayn_design/assets/icons/language.svg
    - packages/xayn_design/assets/icons/legal.svg
    - packages/xayn_design/assets/icons/lightening.svg
    - packages/xayn_design/assets/icons/list.svg
    - packages/xayn_design/assets/icons/loading.svg
    - packages/xayn_design/assets/icons/location_pin.svg
    - packages/xayn_design/assets/icons/map.svg
    - packages/xayn_design/assets/icons/menu.svg
    - packages/xayn_design/assets/icons/minus.svg
    - packages/xayn_design/assets/icons/moon.svg
    - packages/xayn_design/assets/icons/moon_and_sun.svg
    - packages/xayn_design/assets/icons/move.svg
    - packages/xayn_design/assets/icons/neutral.svg
    - packages/xayn_design/assets/icons/new_tab.svg
    - packages/xayn_design/assets/icons/news.svg
    - packages/xayn_design/assets/icons/notification.svg
    - packages/xayn_design/assets/icons/person_active.svg
    - packages/xayn_design/assets/icons/phone.svg
    - packages/xayn_design/assets/icons/plant.svg
    - packages/xayn_design/assets/icons/play.svg
    - packages/xayn_design/assets/icons/plus.svg
    - packages/xayn_design/assets/icons/qr_code.svg
    - packages/xayn_design/assets/icons/qr_scanner.svg
    - packages/xayn_design/assets/icons/reader_mode.svg
    - packages/xayn_design/assets/icons/reload.svg
    - packages/xayn_design/assets/icons/rocket.svg
    - packages/xayn_design/assets/icons/search.svg
    - packages/xayn_design/assets/icons/search_active.svg
    - packages/xayn_design/assets/icons/share_android.svg
    - packages/xayn_design/assets/icons/share_ios.svg
    - packages/xayn_design/assets/icons/shield.svg
    - packages/xayn_design/assets/icons/speech_bubbles.svg
    - packages/xayn_design/assets/icons/sun.svg
    - packages/xayn_design/assets/icons/tabs.svg
    - packages/xayn_design/assets/icons/thumbs_down.svg
    - packages/xayn_design/assets/icons/thumbs_down_active.svg
    - packages/xayn_design/assets/icons/thumbs_up.svg
    - packages/xayn_design/assets/icons/thumbs_up_active.svg
    - packages/xayn_design/assets/icons/trash.svg
    - packages/xayn_design/assets/icons/undo.svg
    - packages/xayn_design/assets/icons/video.svg
