name: xayn_design
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/xaynetwork/xayn_design

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: '0.23.0+1'
  flutter_switch: 0.3.2
  provider: 6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.17.0

flutter:
