import 'package:xayn_design/xayn_design.dart';

Set<String> getIconAssets(Linden linden) => {
      linden.assets.icons.confetti,
      linden.assets.icons.play,
      linden.assets.icons.thumbsDown,
      linden.assets.icons.thumbsUp,
      linden.assets.icons.reload,
      linden.assets.icons.cancel,
      linden.assets.icons.qrCode,
      linden.assets.icons.qrScan,
      linden.assets.icons.devices,
      linden.assets.icons.moon,
      linden.assets.icons.moonAndSun,
      linden.assets.icons.rocket,
      linden.assets.icons.lightening,
      linden.assets.icons.shield,
      linden.assets.icons.bug,
      linden.assets.icons.legal,
      linden.assets.icons.info,
      linden.assets.icons.speechBubbles,
      linden.assets.icons.download,
      linden.assets.icons.undo,
      linden.assets.icons.edit,
      linden.assets.icons.share,
      linden.assets.icons.bookmarkActive,
      linden.assets.icons.bookmark,
      linden.assets.icons.filtersIconRound,
      linden.assets.icons.heart,
      linden.assets.icons.alert,
      linden.assets.icons.check,
      linden.assets.icons.neutral,
      linden.assets.icons.cross,
      linden.assets.icons.plus,
      linden.assets.icons.newTab,
      linden.assets.icons.binoculars,
      linden.assets.icons.home,
      linden.assets.icons.search,
      linden.assets.icons.book,
      linden.assets.icons.readerMode,
      linden.assets.icons.tabs,
      linden.assets.icons.clock,
      linden.assets.icons.gear,
      linden.assets.icons.forward,
      linden.assets.icons.back,
      linden.assets.icons.up,
      linden.assets.icons.down,
      linden.assets.icons.menu,
      linden.assets.icons.person,
      linden.assets.icons.globe,
      linden.assets.icons.image,
      linden.assets.icons.video,
      linden.assets.icons.news,
      linden.assets.icons.trash,
      linden.assets.icons.filters,
    };

Set<String> getGraphicsAssets(Linden linden) => {
      linden.assets.graphics.listView,
      linden.assets.graphics.gridView,
      linden.assets.graphics.newsOnly,
      linden.assets.graphics.searchNews,
      linden.assets.graphics.searchOnly,
    };

Set<String> getIllustrationsAssets(Linden linden) => {
      linden.assets.illustrations.enableCamera,
      linden.assets.illustrations.brainyEnabled,
      linden.assets.illustrations.brainyDisabled,
    };

Set<String> getLogoAssets(Linden linden) => {
      linden.assets.logo.xayn,
      linden.assets.logo.xaynIcon,
    };
