import 'package:xayn_design/xayn_design.dart';

List<String> getIconAssets() => [
      Linden.assets.icons.confetti,
      Linden.assets.icons.play,
      Linden.assets.icons.thumbsDown,
      Linden.assets.icons.thumbsUp,
      Linden.assets.icons.reload,
      Linden.assets.icons.cancel,
      Linden.assets.icons.qrCode,
      Linden.assets.icons.qrScan,
      Linden.assets.icons.devices,
      Linden.assets.icons.moon,
      Linden.assets.icons.moonAndSun,
      Linden.assets.icons.rocket,
      Linden.assets.icons.lightening,
      Linden.assets.icons.shield,
      Linden.assets.icons.bug,
      Linden.assets.icons.legal,
      Linden.assets.icons.info,
      Linden.assets.icons.speechBubbles,
      Linden.assets.icons.download,
      Linden.assets.icons.undo,
      Linden.assets.icons.edit,
      Linden.assets.icons.share,
      Linden.assets.icons.bookmarkActive,
      Linden.assets.icons.bookmark,
      Linden.assets.icons.filtersIconRound,
      Linden.assets.icons.heart,
      Linden.assets.icons.alert,
      Linden.assets.icons.brainyEnabled,
      Linden.assets.icons.brainyDisabled,
      Linden.assets.icons.check,
      Linden.assets.icons.neutral,
      Linden.assets.icons.cross,
      Linden.assets.icons.plus,
      Linden.assets.icons.newTab,
      Linden.assets.icons.binoculars,
      Linden.assets.icons.home,
      Linden.assets.icons.search,
      Linden.assets.icons.book,
      Linden.assets.icons.readerMode,
      Linden.assets.icons.tabs,
      Linden.assets.icons.clock,
      Linden.assets.icons.gear,
      Linden.assets.icons.forward,
      Linden.assets.icons.back,
      Linden.assets.icons.up,
      Linden.assets.icons.down,
      Linden.assets.icons.menu,
      Linden.assets.icons.person,
      Linden.assets.icons.globe,
      Linden.assets.icons.image,
      Linden.assets.icons.video,
      Linden.assets.icons.news,
      Linden.assets.icons.trash,
      Linden.assets.icons.filters,
    ];

List<String> getGraphicsAssets() => [
      Linden.assets.graphics.listView,
      Linden.assets.graphics.gridView,
      Linden.assets.graphics.newsOnly,
      Linden.assets.graphics.searchNews,
      Linden.assets.graphics.searchOnly,
    ];

List<String> getIllustrationsAssets() => [
      Linden.assets.illustrations.enableCamera,
    ];

List<String> getLogoAssets() => [
      Linden.assets.logo.xayn,
      Linden.assets.logo.xaynIcon,
    ];
